## 1.1 Numpy的基础与安装方法

### 1.1.1 NUmpy入门

### 1.1.2 Python的安装

### 1.1.3 Numpy的安装方式

### 1.1.4 NUmpy入门教程

使用NumPy

In [1]:
import numpy as np

In [2]:
a = np.array([1, 2, 3])
a

array([1, 2, 3])

In [3]:
a * 3

array([3, 6, 9])

In [4]:
a + 2

array([3, 4, 5])

In [5]:
[1, 2, 3] * 3

[1, 2, 3, 1, 2, 3, 1, 2, 3]

In [6]:
b = np.array([2, 2, 0])
b

array([2, 2, 0])

In [7]:
a + b

array([3, 4, 3])

In [8]:
a / b

C:\Users\liye\AppData\Local\Temp\ipykernel_12148\1286629031.py:1: RuntimeWarning: divide by zero encountered in divide
  a / b


array([0.5, 1. , inf])

In [9]:
a * b

array([2, 4, 0])

In [10]:
np.dot(a, b)

6

创建各种数组

In [11]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
np.arange(0, 10, 2) # (起点，终点，间隔)

array([0, 2, 4, 6, 8])

In [13]:
np.linspace(0, 10, 15) # 0~10划分为15等分

array([ 0.        ,  0.71428571,  1.42857143,  2.14285714,  2.85714286,
        3.57142857,  4.28571429,  5.        ,  5.71428571,  6.42857143,
        7.14285714,  7.85714286,  8.57142857,  9.28571429, 10.        ])

In [14]:
c = np.array([[1, 2, 3], [4, 5, 6]]) # 创建二维数组
c

array([[1, 2, 3],
       [4, 5, 6]])

In [15]:
c.shape

(2, 3)

In [16]:
d = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]],
[[13,14,15],[16,17,18],[19,20,21],[22,23,24]]])#还可以创建三维数组
d

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18],
        [19, 20, 21],
        [22, 23, 24]]])

In [17]:
d.shape

(2, 4, 3)

In [18]:
np.sum(c)

21

In [19]:
np.sum(c, axis=1)

array([ 6, 15])

In [20]:
c.reshape(3, 2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [21]:
c.reshape(6, 1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [22]:
c

array([[1, 2, 3],
       [4, 5, 6]])

In [23]:
c.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [24]:
np.transpose(c)

array([[1, 4],
       [2, 5],
       [3, 6]])

In [25]:
np.random.randn()

0.20731033634796958

In [26]:
np.random.rand()

0.5609888380885896

In [27]:
np.random.randn(2, 3)

array([[ 1.63455558, -0.83306391,  1.72663652],
       [ 0.07987933, -0.01368355, -0.02801255]])

索引和切片

In [28]:
a

array([1, 2, 3])

In [29]:
a[0]

1

In [30]:
a[2]

3

In [31]:
a

array([1, 2, 3])

In [32]:
a[1] = 3

In [33]:
a

array([1, 3, 3])

In [34]:
a[1] = 2

In [35]:
a

array([1, 2, 3])

In [36]:
c

array([[1, 2, 3],
       [4, 5, 6]])

In [37]:
c[0, 0]

1

In [38]:
c[0, 2]

3

In [39]:
c[1, 2]

6

In [40]:
d = np.array([0, 5, 2, 7, 1, 9])

In [41]:
d[1:5]

array([5, 2, 7, 1])

In [42]:
d[1:3]

array([5, 2])

In [43]:
d[0:5:2]

array([0, 2, 1])

In [44]:
d[::-1]

array([9, 1, 7, 2, 5, 0])

广播

In [45]:
a

array([1, 2, 3])

In [46]:
c

array([[1, 2, 3],
       [4, 5, 6]])

In [47]:
a + c

array([[2, 4, 6],
       [5, 7, 9]])

In [48]:
a * c

array([[ 1,  4,  9],
       [ 4, 10, 18]])

NumPy的高性能计算

In [49]:
import time # 导入用于处理时间的模块

In [50]:
def calculate_time():
    a = np.random.randn(100000)
    b = list(a) # 转换为列表
    start_time = time.time() #  设置开始时间
    for _ in range(1000):
        sum_1 = np.sum(a)
    print("Using NumPy\t %f sec" % (time.time()-start_time))
    start_time = time.time() # 再次设置开始时间
    for _ in range(1000):
       sum_2 = sum(b)
    print("Not using NumPy\t %f sec" % (time.time()-start_time))

In [51]:
calculate_time()

Using NumPy	 0.029308 sec
Not using NumPy	 3.355573 sec


In [52]:
a = np.random.randn(10000000)

In [53]:
%timeit np.sum(a)

8.78 ms ± 161 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [54]:
%timeit sum(a)

559 ms ± 7.67 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


## 1.2 多维数据结构ndarrray的基础

### 1.2.1 ndarray

### 1.2.2 属性

In [55]:
import numpy as np # 导入NumPy模块

In [56]:
a = np.array([1, 2, 3]) #  生成ndarray实例

In [57]:
type(a) # 确认对象的类

numpy.ndarray

In [58]:
b = np.array([[1, 2, 3], [4, 5, 6]]) # 创建2‐dimensional array(二维数组)

In [59]:
a

array([1, 2, 3])

In [60]:
b # 分别显示所得到的结果如下

array([[1, 2, 3],
       [4, 5, 6]])

In [61]:
b.T #进行转置

array([[1, 4],
       [2, 5],
       [3, 6]])

In [62]:
a.T # 因为a.ndim<2，所以没有变化

array([1, 2, 3])

In [63]:
a.data # 显示内存中的地址

In [64]:
a.dtype # 显示数据的类型

dtype('int32')

In [65]:
a.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False

In [66]:
b.flags #  可以获取各种信息

  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False

In [67]:
a.flat[1] # 显示将a转换为一维数组后其中的第一个元素

2

In [68]:
b.flat[4] # 显示将b转换为一维数组后其中的第四个元素

5

In [69]:
c = np.array([1.-2.6j,2.1+3.j, 4.-3.2j]) # 创建以复数为元素的ndarray实例

In [70]:
c.real # 显示实数部分

array([1. , 2.1, 4. ])

In [71]:
c.imag # 显示虚数部分

array([-2.6,  3. , -3.2])

In [72]:
a.size #元素的数量

3

In [73]:
b.size

6

In [74]:
a.itemsize # 按字节序显示每个元素的字长

4

In [75]:
b.itemsize # 在某些环境中可能是4

4

In [76]:
c.size, c.itemsize

(3, 16)

In [77]:
a.nbytes # 按字节序显示数组的长度，在某些环境中可能是12

12

In [78]:
b.nbytes #  在某些环境中可能是24

24

In [79]:
c.nbytes

48

In [80]:
a.size * a.itemsize == a.nbytes #  这个等式成立

True

In [81]:
a.ndim # 显示维数

1

In [82]:
b.ndim

2

In [83]:
a.shape # 显示形状

(3,)

In [84]:
b.shape # 显示形状

(2, 3)

In [85]:
d = np.array([[[2,3,2],[2,2,2]],[[4,3,2],[5,7,1]]]) # 生成三维数组

In [86]:
d.shape, d.ndim # 显示形状和维数

((2, 2, 3), 3)

In [87]:
a.strides  #在各个维度方向上(axis=ndim,axis=ndim-1,…
# axis=1,axis=0)移动到下一个元素所需移动的字节数。在某些环境下可能为(4,)

(4,)

In [88]:
b.strides #  .ndim=2，在某些环境下可能为(12, 4)

(12, 4)

In [89]:
c.strides # .ndim = 3

(16,)

In [90]:
d.strides # .ndim=3在某些环境下可能为(24,12,4)

(24, 12, 4)

In [91]:
a.ctypes.data #  使用ctypes模块的操作

1976086109824

In [92]:
a.base # a的基类数组在什么地方

In [93]:
e = a[:2]

In [94]:
e.base

array([1, 2, 3])

In [95]:
e.base is a

True

In [96]:
a.base is e.base

False

### 1.2.3 内存布局

### 1.2.4 步长

In [97]:
a = np.random.randn(100,100)

In [98]:
b = np.array(a, order='C') # 行主序

In [99]:
c = np.array(a, order='F') # column-major

In [100]:
b.strides, c.strides #从步长上看，二者是相反的

((800, 8), (8, 800))

In [101]:
np.allclose(b, c)      # 确认数组的元素是否完全相同

True

In [102]:
x = np.ones((100000,)) #将所有的元素都初始化为1

In [103]:
y = np.ones((100000*100,))[::100] # 每隔100个元素进行读取

In [104]:
x.strides # 为了移动到相邻的下一个元素，需要跳转8个字节的距离

(8,)

In [105]:
y.strides #为了移动到相邻的下一个元素，需要跳转800个字节的距离

(800,)

In [106]:
x.shape, y.shape

((100000,), (100000,))

In [107]:
%timeit x.sum() # 很明显这个速度更快

26.7 µs ± 150 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [108]:
%timeit y.sum()

82.2 µs ± 1.56 µs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [109]:
y_copy = np.copy(np.ones((100000*100,))[::100])

In [110]:
y_copy.strides

(8,)

In [111]:
%timeit y_copy.sum()

27 µs ± 120 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


### 1.2.5 广播

In [112]:
a=np.array([1, 2, 3])
a

array([1, 2, 3])

In [113]:
b=np.array([[1, 1, 1],[2, 4, 1]]) # 二维数组
b

array([[1, 1, 1],
       [2, 4, 1]])

In [114]:
b + a #  使用广播功能

array([[2, 3, 4],
       [3, 6, 4]])

## 1.3 广播

### 1.3.1 何谓广播

In [115]:
import numpy as np

In [116]:
np.array([[1, 2, 3]]) + [1]

array([[2, 3, 4]])

### 1.3.2 广播的运行机制

In [117]:
a = np.array([[1, 2]])
a

array([[1, 2]])

In [118]:
a.shape

(1, 2)

In [119]:
b = np.array([3, 4])
b

array([3, 4])

In [120]:
b.shape

(2,)

In [121]:
a + b

array([[4, 6]])

In [122]:
a = np.array([1, 2])

In [123]:
b = np.array([[3, 4],[2, 3]])

In [124]:
a

array([1, 2])

In [125]:
b

array([[3, 4],
       [2, 3]])

In [126]:
a.shape

(2,)

In [127]:
b.shape

(2, 2)

In [128]:
a + b

array([[4, 6],
       [3, 5]])

In [129]:
a = np.array([[2], [1]])

In [130]:
b = np.array([5])

In [131]:
c = np.array([[[1, 2, 3], [4, 5, 6]],[[7, 8, 9], [10, 11, 12]]])

In [132]:
a

array([[2],
       [1]])

In [133]:
b

array([5])

In [134]:
c

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [135]:
a.shape

(2, 1)

In [136]:
b.shape

(1,)

In [137]:
c.shape

(2, 2, 3)

In [138]:
a + b + c

array([[[ 8,  9, 10],
        [10, 11, 12]],

       [[14, 15, 16],
        [16, 17, 18]]])

## 1.4 切片

In [139]:
a = [1, 2, 3, 4, 5]

In [140]:
a[1:-1]

[2, 3, 4]

### 1.4.1 何谓切片

### 1.4.2 切片的使用方法

In [141]:
import numpy as np

In [142]:
a = np.arange(15)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [143]:
a[5:11:2]

array([5, 7, 9])

In [144]:
a = np.arange(10) #  创建包含10个连号数据的数组
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [145]:
a[1:5] # 1～4

array([1, 2, 3, 4])

In [146]:
a[2:8:2] #  2~7每隔一个

array([2, 4, 6])

In [147]:
a[::-1] # 逆序排列

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [148]:
a[:3] # 0～2

array([0, 1, 2])

In [149]:
a[4:] # 4～9

array([4, 5, 6, 7, 8, 9])

In [150]:
a[:3],a[3:] # 将3作为边界划分为两个数组

(array([0, 1, 2]), array([3, 4, 5, 6, 7, 8, 9]))

In [151]:
a[::2] # 指定间隔一个元素

array([0, 2, 4, 6, 8])

In [152]:
a[:] # 指定全范围内的数据

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### 1.4.3 向高维数据结构扩展

二维数组

In [153]:
b = np.arange(20).reshape(4,5) # 4×5的二维数组
b

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [154]:
b[1:3, 2:4] # 将第1~2行，第2~3列提取出来

array([[ 7,  8],
       [12, 13]])

In [155]:
b[:2, 1:] #  将第0~1行，第1~4列提取出来

array([[1, 2, 3, 4],
       [6, 7, 8, 9]])

In [156]:
b[::2, :] # 在行方向上每隔一个提取元素

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14]])

In [157]:
b[:, ::2] # 在列方向上每隔一个提取元素

array([[ 0,  2,  4],
       [ 5,  7,  9],
       [10, 12, 14],
       [15, 17, 19]])

In [158]:
b[:, ::-1] # 逆順

array([[ 4,  3,  2,  1,  0],
       [ 9,  8,  7,  6,  5],
       [14, 13, 12, 11, 10],
       [19, 18, 17, 16, 15]])

In [159]:
b[::-1, ::-1] # 全部颠倒过来

array([[19, 18, 17, 16, 15],
       [14, 13, 12, 11, 10],
       [ 9,  8,  7,  6,  5],
       [ 4,  3,  2,  1,  0]])

三维数组

In [160]:
c = np.zeros((3, 4, 5)) #  3×4×5的三维数组
c

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [161]:
c[1:, 1:4, :] = 1
c

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[0., 0., 0., 0., 0.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [162]:
c = np.zeros((3, 4, 5)) # 重置

In [163]:
c[:, 1:2, 3:] = 1
c

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 1., 1.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 1., 1.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 1., 1.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [164]:
c = np.zeros((3, 4, 5)) # 重置

In [165]:
c[:, :, ::2] = 1 #  每两个一次
c

array([[[1., 0., 1., 0., 1.],
        [1., 0., 1., 0., 1.],
        [1., 0., 1., 0., 1.],
        [1., 0., 1., 0., 1.]],

       [[1., 0., 1., 0., 1.],
        [1., 0., 1., 0., 1.],
        [1., 0., 1., 0., 1.],
        [1., 0., 1., 0., 1.]],

       [[1., 0., 1., 0., 1.],
        [1., 0., 1., 0., 1.],
        [1., 0., 1., 0., 1.],
        [1., 0., 1., 0., 1.]]])

In [166]:
c = np.zeros((3, 4, 5)) #  重置

In [167]:
c[::2, ::2, ::2] = 1
c

array([[[1., 0., 1., 0., 1.],
        [0., 0., 0., 0., 0.],
        [1., 0., 1., 0., 1.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[1., 0., 1., 0., 1.],
        [0., 0., 0., 0., 0.],
        [1., 0., 1., 0., 1.],
        [0., 0., 0., 0., 0.]]])

## 1.5 关于坐标轴和维度

### 1.5.1 ndarray的维度

In [168]:
import numpy as np

In [169]:
a = np.array([[1, 2, 3], [4, 5, 6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [170]:
a.shape

(2, 3)

In [171]:
a.ndim

2

### 1.5.2 关于坐标系

In [172]:
a = np.arange(6).reshape((3, 2))
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [173]:
a.shape

(3, 2)

In [174]:
b = np.array([a, a])
b

array([[[0, 1],
        [2, 3],
        [4, 5]],

       [[0, 1],
        [2, 3],
        [4, 5]]])

In [175]:
b.shape

(2, 3, 2)

### 1.5.3 作为函数参数的axis

In [176]:
b.sum(axis=0)

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10]])

In [177]:
b.sum(axis=0).shape

(3, 2)

In [178]:
b.sum(axis=1)

array([[6, 9],
       [6, 9]])

In [179]:
b.sum(axis=1).shape

(2, 2)

In [180]:
b.sum(axis=2)

array([[1, 5, 9],
       [1, 5, 9]])

In [181]:
b.sum(axis=2).shape

(2, 3)

## 1.6 ndarray的shape属性

In [182]:
import numpy as np

In [183]:
a = np.array([5, 3, 8, 9])
a

array([5, 3, 8, 9])

In [184]:
a.shape

(4,)

In [185]:
a = np.array([5, 3, 8, 9])

In [186]:
b = a.reshape((2, 2))
b

array([[5, 3],
       [8, 9]])

In [187]:
b.shape

(2, 2)

In [188]:
a

array([5, 3, 8, 9])

In [189]:
a.shape

(4,)

In [190]:
a.shape = (4, 1)

In [191]:
a

array([[5],
       [3],
       [8],
       [9]])

In [192]:
c = np.arange(12).reshape((3, 4))
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [193]:
c.shape=(1, 12)
c

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]])

In [194]:
# c.shape = (13,) # 如果元素数量不正确，则会返回错误

In [195]:
a = np.array([1, 2, 3, 4, 5]) #  简单的一维数组

In [196]:
a.shape

(5,)

In [197]:
b = np.array([[1], [2], [3], [4], [5]]) # 如果转换为纵向量其shape就变为(R,1)

In [198]:
b.shape

(5, 1)

## 1.7 元素数据类型的种类与指定方法

### 1.7.1 需要dtype的理由

### 1.7.2 数据类型

In [199]:
import numpy as np

In [200]:
a = np.array([0, 1, 2]) # 首先在什么都不指定的情况下生成数组
a

array([0, 1, 2])

In [201]:
a.dtype #首先在什么都不指定的情况下生成数组

dtype('int32')

In [202]:
b = np.array([0, 1, 2], dtype='int32') # 尝试减少位数
b

array([0, 1, 2])

In [203]:
b.dtype

dtype('int32')

In [204]:
c = np.array([0, 1, 2], dtype='float') # float和int的默认位数是64
c

array([0., 1., 2.])

In [205]:
# d = np.array([3e50, 4e35], dtype='int64') #  如果位数太大，无法使用'int'表示时会产生溢出错误

In [206]:
d = np.array([3e50, 4e35], dtype='float64') #  如果改成float，就可以成功地生成数组

In [207]:
e = np.array([3.5, 4.2, -4.3], dtype='int') # 即使是使用小数表示的数组，如果数据类型被设置为int，则只有整数部分被保留
e

array([ 3,  4, -4])

In [208]:
f = np.array([0, 3, 0, -1], dtype = 'bool') #将0转换为False，如果不是0，则转换为True
f

array([False,  True, False,  True])

In [209]:
g = np.array([0., 1., 2.], dtype='int64')
g

array([0, 1, 2], dtype=int64)

In [210]:
g.dtype = 'int32' # 将数据类型转换为int32
g

array([0, 0, 1, 0, 2, 0])

In [211]:
g.dtype = 'float64' #将数据类型转换为float64
g

array([0.e+000, 5.e-324, 1.e-323])

In [212]:
g.dtype = 'float32' # 将位数转换为32
g

array([0.e+00, 0.e+00, 1.e-45, 0.e+00, 3.e-45, 0.e+00], dtype=float32)

In [213]:
g.dtype = 'int64' #  将数据类型恢复为原有类型，则数据的值也会恢复
g

array([0, 1, 2], dtype=int64)

In [214]:
h = np.random.randint(10, size=100, dtype='int8') # 生成100个0~9的整数。数据类型是'int8'

In [215]:
i = np.random.randint(10, size=100, dtype='int64') #  将位数设置为64

In [216]:
h.nbytes # 确认字节数

100

In [217]:
i.nbytes #  变为h的8倍

800

## 1.8 副本和试图的区别

### 1.8.1 副本和视图

In [218]:
a = np.array([1, 2, 3])

In [219]:
d = a.view() #创建视图

In [220]:
d[0] = 100 # 改变视图中的一个值
d

array([100,   2,   3])

In [221]:
a # 原有数组a中的数据也被改变了

array([100,   2,   3])

In [222]:
c = a.copy()
c

array([100,   2,   3])

In [223]:
c[1] = 25
c

array([100,  25,   3])

In [224]:
a

array([100,   2,   3])

### 1.8.2 不同操作方式的区别

带入

In [225]:
a = np.array([1, 2, 3])

In [226]:
b = a # 将a代入b中

In [227]:
id(a) == id(b) # 确认引用的内存地址是否相同

True

In [228]:
a = np.array([1, 2, 3])

In [229]:
c = a[:] #  换一种语法

In [230]:
id(a) == id(c) #可以看出引用的是不同的对象

False

In [231]:
c[1] = 22 # 修改c的一部分

In [232]:
a # 对c做的修改也在a中被反映了出来

array([ 1, 22,  3])

In [233]:
d = a[:1]

In [234]:
id(d) == id(a)

False

In [235]:
d[0] = 11

In [236]:
a

array([11, 22,  3])

In [237]:
d

array([11])

In [238]:
e = a.copy() #代入a的副本

In [239]:
e.base is a

False

In [240]:
e[2] = 234

In [241]:
e

array([ 11,  22, 234])

In [242]:
a

array([11, 22,  3])

In [243]:
print(a.base)

None


In [244]:
f = a.copy()

In [245]:
f.base is a

False

运算

In [246]:
a = np.array([1, 2, 3])

In [247]:
c = a # 创建作为视图的变量c

In [248]:
a = a + 1 #加1

In [249]:
c # 加法运算没有被反映到c中

array([1, 2, 3])

In [250]:
a

array([2, 3, 4])

In [251]:
a = np.array([1, 2, 3])

In [252]:
c = a

In [253]:
a += 1

In [254]:
c

array([2, 3, 4])

In [255]:
a

array([2, 3, 4])

In [256]:
a = np.array([1, 2, 3])

In [257]:
c = a

In [258]:
np.add(a, 1, out=a)

array([2, 3, 4])

In [259]:
a

array([2, 3, 4])

In [260]:
c

array([2, 3, 4])

In [261]:
def test():
    import numpy as np
    import time
    X = np.ones(100000000, dtype='int8')
    Y = np.ones(100000000, dtype='int8')
    a = time.time()
    for _ in range(100):
        X = X*4 + Y*3
        X = np.ones(100000000, dtype='int8')
    b = time.time()
    print('X = X*4 + Y*3: {} sec'.format((b-a)/100))
    a = time.time()
    for _ in range(100):
        X *= 4
        X += Y*3
        X = np.ones(100000000, dtype='int8')
    b = time.time()
    print('X *= 4; X += Y*3: {} sec'.format((b-a)/100))
    a = time.time()
    for _ in range(100):
        np.multiply(X, 4, out=X)
        np.multiply(Y, 3, out=Y)
        np.add(X, Y, out=X)
        X = np.ones(100000000, dtype='int8')
    b = time.time()
    print("using functions: {} sec".format((b-a)/100))

In [262]:
test()

X = X*4 + Y*3: 0.17634028673171998 sec
X *= 4; X += Y*3: 0.15253691196441652 sec
using functions: 0.1523624014854431 sec


### 1.8.3 数组的扁平化

In [263]:
a = np.random.randn(2, 3, 9)
a

array([[[ 0.85770221, -1.22082058,  1.03731578, -0.66671716,
         -0.09976111, -1.88545977, -0.23333362, -2.72680473,
          0.59206768],
        [-1.09423737, -1.98554731, -0.13119044,  0.19168362,
          0.6471814 ,  0.75030572,  1.10660154, -0.00707188,
         -0.67881074],
        [-0.39104172,  1.09496789,  0.66010987, -0.82016842,
          1.61344255, -1.2331649 , -1.89640352,  0.17364301,
          0.76803879]],

       [[-0.2294114 ,  1.78540167, -0.60735757,  0.31260949,
         -0.74483745, -2.51015143,  0.24709745, -1.78462749,
          0.50335216],
        [-0.92259944,  1.97373801, -0.81499703, -1.95896677,
         -0.12080693,  0.51800541, -0.71098474, -0.6131706 ,
         -0.41451167],
        [-0.33161393, -1.94436578, -1.25217883,  0.01049303,
          1.64369254,  1.81085525, -0.91047832,  0.67924843,
          1.38327459]]])

In [264]:
b = a.ravel()

In [265]:
c = a.flatten()
c

array([ 0.85770221, -1.22082058,  1.03731578, -0.66671716, -0.09976111,
       -1.88545977, -0.23333362, -2.72680473,  0.59206768, -1.09423737,
       -1.98554731, -0.13119044,  0.19168362,  0.6471814 ,  0.75030572,
        1.10660154, -0.00707188, -0.67881074, -0.39104172,  1.09496789,
        0.66010987, -0.82016842,  1.61344255, -1.2331649 , -1.89640352,
        0.17364301,  0.76803879, -0.2294114 ,  1.78540167, -0.60735757,
        0.31260949, -0.74483745, -2.51015143,  0.24709745, -1.78462749,
        0.50335216, -0.92259944,  1.97373801, -0.81499703, -1.95896677,
       -0.12080693,  0.51800541, -0.71098474, -0.6131706 , -0.41451167,
       -0.33161393, -1.94436578, -1.25217883,  0.01049303,  1.64369254,
        1.81085525, -0.91047832,  0.67924843,  1.38327459])

In [266]:
a

array([[[ 0.85770221, -1.22082058,  1.03731578, -0.66671716,
         -0.09976111, -1.88545977, -0.23333362, -2.72680473,
          0.59206768],
        [-1.09423737, -1.98554731, -0.13119044,  0.19168362,
          0.6471814 ,  0.75030572,  1.10660154, -0.00707188,
         -0.67881074],
        [-0.39104172,  1.09496789,  0.66010987, -0.82016842,
          1.61344255, -1.2331649 , -1.89640352,  0.17364301,
          0.76803879]],

       [[-0.2294114 ,  1.78540167, -0.60735757,  0.31260949,
         -0.74483745, -2.51015143,  0.24709745, -1.78462749,
          0.50335216],
        [-0.92259944,  1.97373801, -0.81499703, -1.95896677,
         -0.12080693,  0.51800541, -0.71098474, -0.6131706 ,
         -0.41451167],
        [-0.33161393, -1.94436578, -1.25217883,  0.01049303,
          1.64369254,  1.81085525, -0.91047832,  0.67924843,
          1.38327459]]])

In [267]:
a[0,0,0] = 129

In [268]:
a[0,0,0], b[0], c[0]

(129.0, 129.0, 0.8577022137262913)

### 1.8.4 fancy indexing

In [269]:
a = np.random.randint(10, size=100)
a

array([5, 4, 4, 3, 8, 8, 9, 8, 7, 4, 7, 6, 6, 5, 2, 0, 1, 5, 2, 6, 7, 2,
       4, 7, 7, 1, 3, 1, 3, 0, 8, 0, 0, 8, 5, 5, 3, 6, 3, 4, 0, 3, 0, 5,
       8, 2, 8, 6, 3, 8, 5, 6, 7, 7, 5, 9, 7, 4, 2, 9, 8, 6, 6, 8, 6, 9,
       7, 9, 1, 4, 7, 3, 5, 6, 1, 9, 9, 3, 3, 9, 0, 5, 3, 5, 6, 3, 4, 6,
       5, 0, 7, 3, 1, 4, 0, 6, 9, 1, 1, 5])

In [270]:
n = a%3==0 # 3的倍数的位置上是True
n

array([False, False, False,  True, False, False,  True, False, False,
       False, False,  True,  True, False, False,  True, False, False,
       False,  True, False, False, False, False, False, False,  True,
       False,  True,  True, False,  True,  True, False, False, False,
        True,  True,  True, False,  True,  True,  True, False, False,
       False, False,  True,  True, False, False,  True, False, False,
       False,  True, False, False, False,  True, False,  True,  True,
       False,  True,  True, False,  True, False, False, False,  True,
       False,  True, False,  True,  True,  True,  True,  True,  True,
       False,  True, False,  True,  True, False,  True, False,  True,
       False,  True, False, False,  True,  True,  True, False, False,
       False])

In [271]:
a[n] #将3的倍数的元素提取出来

array([3, 9, 6, 6, 0, 6, 3, 3, 0, 0, 0, 3, 6, 3, 0, 3, 0, 6, 3, 6, 9, 9,
       6, 6, 6, 9, 9, 3, 6, 9, 9, 3, 3, 9, 0, 3, 6, 3, 6, 0, 3, 0, 6, 9])

In [272]:
k = a[n]

In [273]:
np.may_share_memory(a, k) #  用于确认内存是否是共享的函数。详细内容将在1.8.5小节中进行讲解

False

In [274]:
f = a[np.arange(0, 10, 2)]

In [275]:
np.may_share_memory(a, f)

False

### 1.8.5 副本和试图的分辨方法

In [276]:
a = np.array([1, 2, 3])

In [277]:
b = a

In [278]:
c = b

In [279]:
d = a.copy()

In [280]:
np.may_share_memory(a, b) # 如果是True，则说明b是a的视图

True

In [281]:
np.may_share_memory(a, c) # 这里也返回True

True

In [282]:
np.may_share_memory(a, d) #  由于d是a的副本，因此返回False

False

In [283]:
np.shares_memory(a, b) # 更严谨的判断使用share_memory函数

True

In [284]:
np.shares_memory(a, d)

False