## 12.1 非线性决策边界

## 12.2 前馈人工神经网络和反馈人工神经网络

## 12.3 多层感知机

## 12.4 训练多层感知机

### 12.4.1 反向传播

### 12.4.2 训练一个多层感知机逼近 XOR 函数

代码 12.1

In [1]:
from sklearn.model_selection import train_test_split
from sklearn.neural_network import MLPClassifier

y = [0, 1, 1, 0]
X = [[0, 0], [0, 1], [1, 0], [1, 1]]
clf = MLPClassifier(solver='lbfgs', activation='logistic', hidden_layer_sizes=(2,), random_state=20)
clf.fit(X, y)
predictions = clf.predict(X)
print('Accuracy: %s' % clf.score(X, y))
for i, p in enumerate(predictions):
    print('True: %s, Predicted: %s' % (y[i], p))

Accuracy: 1.0
True: 0, Predicted: 0
True: 1, Predicted: 1
True: 1, Predicted: 1
True: 0, Predicted: 0


代码 12.2

In [2]:
print('Weights connecting the input layer and the hidden layer: \n%s' %clf.coefs_[0])
print('Hidden layer bias weights: \n%s' % clf.intercepts_[0])
print('Weights connecting the hidden layer and the output layer:\n%s' % clf.coefs_[1])
print('Output layer bias weight: \n%s' % clf.intercepts_[1])

Weights connecting the input layer and the hidden layer: 
[[6.11803923 6.35656372]
 [5.79147877 6.14551934]]
Hidden layer bias weights: 
[-9.38637924 -2.77751745]
Weights connecting the hidden layer and the output layer:
[[-14.95481822]
 [ 14.53080971]]
Output layer bias weight: 
[-7.22845322]


### 12.4.3 训练一个多层感知机分类手写数字

代码 12.3

http://yann.lecun.com/exdb/mnist/

In [3]:
import gzip
import matplotlib.pyplot as plt
import matplotlib.cm as cm
import numpy as np

# 定义加载图像数据的函数
def load_mnist_images(image_path):
    with gzip.open(image_path, 'rb') as f:
        # 跳过文件头
        f.read(16)
        # 读取图像数据
        buf = f.read()
        # 将数据转换为NumPy数组
        data = np.frombuffer(buf, dtype=np.uint8).reshape(-1, 28, 28)
    return data

# 定义加载标签数据的函数
def load_mnist_labels(label_path):
    with gzip.open(label_path, 'rb') as f:
        # 跳过文件头
        f.read(8)
        # 读取标签数据
        buf = f.read()
        # 将数据转换为NumPy数组
        labels = np.frombuffer(buf, dtype=np.uint8)
    return labels

In [4]:

from sklearn.model_selection import cross_val_score
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.neural_network import MLPClassifier

mnist_data = load_mnist_images("data\\mnist\\t10k-images-idx3-ubyte.gz")
mnist_target = load_mnist_labels("data\\mnist\\t10k-labels-idx1-ubyte.gz")
X = mnist_data
X = X.reshape(X.shape[0], -1)  # Reshape X to (n_samples, n_features)
y = mnist_target
pipeline = Pipeline([('ss', StandardScaler()),
                     ('mlp', MLPClassifier(hidden_layer_sizes=(150, 100), alpha=0.1, max_iter=300, random_state=20))])
print(cross_val_score(pipeline, X, y, n_jobs=-1))

[0.945  0.9365 0.9505 0.9695 0.9635]
